args:
  comet: True
  seed: 48
  use_json_split: True
  deterministic_algorithms: False
  use_random_sampler: False
  data: data/china
  val_data: data/china
  cache_dir: data/cached_datasets
  clear_cache: False
  scheduler_name: warmup
  warmup_steps: 0  
  first_cycle_steps: 1.0    
  scheduler_gamma: 0.5
  stop_early: False
  patience: 4
  delta: 0.001
  classes: 33
  seg_loss_name: DiceCELoss
  classification_loss: cross_entropy #Options: cross_entropy, focal_loss, sice_loss
  correctnes_term: False
  focal_gamma: 0.5
  weighted_cls: True
  include_background_loss: True
  include_background_metrics: False
  include_background_gwd: True
  keys: 
    - image
    - label
  epochs: 1001
  patch_size: 
    - 128
    - 128
    - 128
  spatial_crop_size: 
    - 224
    - 192
    - 160
  spatial_crop_margin:
    - 32
    - 32
    - 32
  crop_foreground: True
  batch_size: 2
  batch_size_val: 1
  crop_samples: 2 #batch_size * crop_samples = 4
  pixdim: 0.4
  houndsfield_clip: 5000    
  z_score_norm: False  
  rotation_range: 0.1
  num_threads: 8
  pin_memory: False
  n_features: 32
  unet_depth: 5
  norm: instance
  lr: 1.0e-3
  min_lr: 1.0e-6
  weight_decay: 1.0e-4
  background_weight: 0.1
  background_penalty: 2.0
  optimizer: AdamW
  adam_eps: 1.0e-8
  adam_ams: False
  gradient_accumulation: 1
  parallel: False
  gpu_frac: 0.999
  trained_model: null
  continue_training: False
  trained_model: null
  use_scaler: False
  autocast_dtype: float32
  grad_clip: True 
  max_grad_norm: 1.0
  save_checkpoints: True
  checkpoint_dir: experiments
  save_interval: 100
  save_optimiser_interval: 200
  save_optimizer: True           
  start_epoch: 0
  print_config: False
  tags: experiment#classes32#GWD#Dice#CE
  device: cuda
  visible_devices: 0,1
  cuda_device_id: 1
  deterministic_algorithms: False
  is_log_image: True
  is_log_3d: True
  validation_interval: 20
  log_batch_interval: 10
  log_metrics_interval: 10
  log_slice_interval: 10
  log_3d_scene_interval_training: 100
  log_3d_scene_interval_validation: 100
  multiclass_metrics_interval: 100
  multiclass_metrics_epoch: 100